### ISSUE TITLE
Change name of scheme

### ISSUE THREAD

**Issue by stefan2904** [Romibuzi/pycharm-color-scheme#1]
Thanks a lot the your effort of adapting the scheme!
A small suggestion:

In the scheme it says 

```
name="Pycharm"
```

You may want to change it, to something like:

```
name="Flatland"
```

thx!

**Comment by stefan2904** [comment]
... or just merge PR #2 ;)

**Comment by romibuzi** [comment]
hey @stefan2904 ! iThank you for the PR, i've just merged it
